import Head from 'next/head'
import Image from 'next/image'
//import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
    <style jsx>{
    `
    .container {
      padding: 0 2rem;
    }
    
    .main {
      min-height: 100vh;
      padding: 4rem 0;
      flex: 1;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
    }
    
    .footer {
      display: flex;
      flex: 1;
      padding: 2rem 0;
      border-top: 1px solid #eaeaea;
      justify-content: center;
      align-items: center;
    }
    
    .footer a {
      display: flex;
      justify-content: center;
      align-items: center;
      flex-grow: 1;
    }
    
    .title a {
      color: #0070f3;
      text-decoration: none;
    }
    
    .title a:hover,
    .title a:focus,
    .title a:active {
      text-decoration: underline;
    }
    
    .title {
      margin: 0;
      line-height: 1.15;
      font-size: 4rem;
    }
    
    .title,
    .description {
      text-align: center;
    }
    
    .description {
      margin: 4rem 0;
      line-height: 1.5;
      font-size: 1.5rem;
    }
    
    .code {
      background: #fafafa;
      border-radius: 5px;
      padding: 0.75rem;
      font-size: 1.1rem;
      font-family: Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono,
        Bitstream Vera Sans Mono, Courier New, monospace;
    }
    
    .grid {
      display: flex;
      align-items: center;
      justify-content: center;
      flex-wrap: wrap;
      max-width: 800px;
    }
    
    .card {
      margin: 1rem;
      padding: 1.5rem;
      text-align: left;
      color: inherit;
      text-decoration: none;
      border: 1px solid #eaeaea;
      border-radius: 10px;
      transition: color 0.15s ease, border-color 0.15s ease;
      max-width: 300px;
    }
    
    .card:hover,
    .card:focus,
    .card:active {
      color: #0070f3;
      border-color: #0070f3;
    }
    
    .card h2 {
      margin: 0 0 1rem 0;
      font-size: 1.5rem;
    }
    
    .card p {
      margin: 0;
      font-size: 1.25rem;
      line-height: 1.5;
    }
    
    .logo {
      height: 1em;
      margin-left: 0.5rem;
    }
    
    @media (max-width: 600px) {
      .grid {
        width: 100%;
        flex-direction: column;
      }
    }
    
    
    
    `
  } 
    
    </style>
    <div className="container">
      <Head>
        <title>QuickQ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
      <div className="wrapper">
      <div class="title-text">
        <div class="title login">Login</div>
        <div class="title signup">Sign up</div>
      </div>
      <div class="form-container">
        <div class="slide-controls">
          <input type="radio" name="slide" id="login" checked/>
          <input type="radio" name="slide" id="signup"/>
          <label for="login" class="slide login">Login</label>
          <label for="signup" class="slide signup">Signup</label>
          <div class="slider-tab"></div>
        </div>
        <div class="form-inner">
          <form action="#" class="login">
            <div class="field">
              <input type="text" placeholder="Email Address" required/>
            </div>
            <div class="field">
              <input type="password" placeholder="Password" required/>
            </div>
            <div class="pass-link"><a href="#">Forgot password?</a></div>
            <div class="field btn">
              <div class="btn-layer"></div>
              <input type="submit" value="Login"/>
            </div>
            <div class="signup-link">New to QuickQ? <a href="">Signup now</a></div>
          </form>
          <form action="#" class="signup">
            <div class="field">
              <input type="text" placeholder="Email Address" required/>
            </div>
            <div class="field">
              <input type="password" placeholder="Password" required/>
            </div>
            <div class="field">
              <input type="password" placeholder="Confirm password" required/>
            </div>
            <div class="field btn">
              <div class="btn-layer"></div>
              <input type="submit" value="Signup"/>
            </div>
          </form>
        </div>
      </div>
    </div>
      </main>
      </div>
</>
  )
}
